;; Add the modules folder to the load path
(add-to-list 'load-path (expand-file-name "modules/" user-emacs-directory))

(require 'marek-cheatsheet)
(require 'marek-completion)
(require 'marek-general-keys)
(require 'marek-general-settings)
(require 'marek-git)
(require 'marek-ledger-mode)
(require 'marek-markdown-mode)
(require 'marek-org-mode)
(require 'marek-popup-menu)
(require 'marek-projects)
(require 'marek-theme)
(require 'marek-window-management)
